mod common;

use common::Fixture;
use grove::render::{self, Context};
use grove::{config, resolve};
use std::collections::BTreeMap;

fn context() -> Context {
    Context {
        slug: "mon_2695".into(),
        ports: BTreeMap::from([("frontend".into(), 24310u16), ("backend".into(), 24311u16)]),
        db_name: Some("mondrio_mon_2695".into()),
        main_worktree: "/home/carraes/mondrio/mondrio-platform".into(),
    }
}

fn set(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
    pairs
        .iter()
        .map(|(k, v)| (k.to_string(), v.to_string()))
        .collect()
}

#[test]
fn rewrites_a_key_in_place_and_leaves_its_neighbours_alone() {
    let source = "DEBUG=True\nVITE_API_URL=http://localhost:8000\nSENTRY_DSN=https://real\n";

    let out = render::env(
        source,
        &set(&[("VITE_API_URL", "http://localhost:{{ port.backend }}")]),
        &context(),
    )
    .expect("render");

    assert!(out.contains("VITE_API_URL=http://localhost:24311\n"));
    assert!(out.contains("DEBUG=True\n"));
    assert!(out.contains("SENTRY_DSN=https://real\n"));
    assert!(!out.contains("localhost:8000"));
}

#[test]
fn appends_a_key_the_source_never_had() {
    let source = "DEBUG=True\n";

    let out = render::env(
        source,
        &set(&[("MONGODB_DATABASE", "{{ db.name }}")]),
        &context(),
    )
    .expect("render");

    assert!(out.contains("MONGODB_DATABASE=mondrio_mon_2695\n"), "{out}");
    assert!(out.contains("DEBUG=True\n"));
}

/// The source is a human's real `.env.local`. Its comments and ordering are how they
/// navigate it, so a rewritten copy has to stay recognisable.
#[test]
fn keeps_comments_and_ordering() {
    let source = "# WorkOS -- ask the CTO for these\nWORKOS__API_KEY=sk_live\n\n# Database\nMONGODB_DATABASE=mondrio\n";

    let out = render::env(
        source,
        &set(&[("MONGODB_DATABASE", "{{ db.name }}")]),
        &context(),
    )
    .expect("render");

    // Past the two-line generated header, the file must read exactly as the source did.
    let body: Vec<&str> = out.lines().skip(2).collect();
    assert_eq!(
        body,
        [
            "# WorkOS -- ask the CTO for these",
            "WORKOS__API_KEY=sk_live",
            "",
            "# Database",
            "MONGODB_DATABASE=mondrio_mon_2695",
        ]
    );
}

/// A commented-out key is not the key. Rewriting it would leave the live value untouched
/// and the instance pointed at the wrong port, silently.
#[test]
fn a_commented_out_key_is_not_mistaken_for_the_real_one() {
    let source = "# VITE_API_URL=http://localhost:9999\nVITE_API_URL=http://localhost:8000\n";

    let out = render::env(
        source,
        &set(&[("VITE_API_URL", "http://localhost:{{ port.backend }}")]),
        &context(),
    )
    .expect("render");

    assert!(
        out.contains("# VITE_API_URL=http://localhost:9999\n"),
        "{out}"
    );
    assert!(
        out.contains("\nVITE_API_URL=http://localhost:24311\n"),
        "{out}"
    );
}

#[test]
fn tolerates_spaces_around_the_equals_sign() {
    let source = "VITE_API_URL = http://localhost:8000\n";

    let out = render::env(
        source,
        &set(&[("VITE_API_URL", "http://localhost:{{ port.backend }}")]),
        &context(),
    )
    .expect("render");

    assert!(out.contains("VITE_API_URL=http://localhost:24311"), "{out}");
    assert!(!out.contains("8000"), "{out}");
}

#[test]
fn marks_the_file_as_generated_so_nobody_edits_it_by_hand() {
    let out = render::env("DEBUG=True\n", &set(&[]), &context()).expect("render");

    assert!(out.starts_with("# generated by grove"), "{out}");
    assert!(
        out.contains("/home/carraes/mondrio/mondrio-platform"),
        "the header must name the source file's checkout: {out}"
    );
}

#[test]
fn every_template_variable_resolves() {
    let out = render::env(
        "",
        &set(&[
            ("SLUG", "{{ slug }}"),
            ("PORT", "{{ port.frontend }}"),
            ("DB", "{{ db.name }}"),
            ("MAIN", "{{ main_worktree }}"),
        ]),
        &context(),
    )
    .expect("render");

    assert!(out.contains("SLUG=mon_2695"), "{out}");
    assert!(out.contains("PORT=24310"), "{out}");
    assert!(out.contains("DB=mondrio_mon_2695"), "{out}");
    assert!(
        out.contains("MAIN=/home/carraes/mondrio/mondrio-platform"),
        "{out}"
    );
}

/// A typo in a port name must not render an empty string into a URL, which would produce
/// `http://localhost:/` and a failure far from its cause.
#[test]
fn an_unknown_template_variable_is_an_error_not_an_empty_string() {
    let err = render::env(
        "",
        &set(&[("VITE_API_URL", "http://localhost:{{ port.backned }}")]),
        &context(),
    )
    .expect_err("must refuse an unknown port name");

    let msg = format!("{err:#}");
    assert!(
        msg.contains("backned"),
        "should name the bad reference: {msg}"
    );
}

const CONFIG: &str = r#"
version = 1

[ports]
names = ["backend"]

[[secrets]]
from = "backend/.env.local"
into = "backend/.env.local"

[secrets.set]
VITE_API_URL = "http://localhost:{{ port.backend }}"
"#;

/// The whole point: the worktree has no `.env.local`, the main checkout does, and the
/// agent has to do nothing about it.
#[test]
fn reads_from_the_main_checkout_and_writes_into_the_worktree() {
    let fx = Fixture::new();
    std::fs::create_dir_all(fx.main.join("backend")).expect("mkdir");
    std::fs::write(
        fx.main.join("backend/.env.local"),
        "WORKOS__API_KEY=sk_live\nVITE_API_URL=http://localhost:8000\n",
    )
    .expect("write main env");

    let wt = fx.add_worktree("mon_2695");
    assert!(
        !wt.join("backend/.env.local").exists(),
        "precondition: a fresh worktree carries no gitignored env"
    );
    let resolved = resolve::resolve(&wt).expect("resolve");
    let cfg = config::parse(CONFIG).expect("parse");

    let written = render::all(&cfg, &resolved, &context()).expect("render all");

    let body = std::fs::read_to_string(wt.join("backend/.env.local")).expect("read written");
    assert_eq!(written, [wt.join("backend/.env.local")]);
    assert!(
        body.contains("VITE_API_URL=http://localhost:24311"),
        "{body}"
    );
    assert!(
        body.contains("WORKOS__API_KEY=sk_live"),
        "secrets must come across untouched: {body}"
    );
    assert_eq!(
        std::fs::read_to_string(fx.main.join("backend/.env.local")).unwrap(),
        "WORKOS__API_KEY=sk_live\nVITE_API_URL=http://localhost:8000\n",
        "the main checkout's env must be untouched"
    );
}

#[test]
fn a_missing_source_names_the_main_checkout_it_looked_in() {
    let fx = Fixture::new();
    let wt = fx.add_worktree("mon_2695");
    let resolved = resolve::resolve(&wt).expect("resolve");
    let cfg = config::parse(CONFIG).expect("parse");

    let err = render::all(&cfg, &resolved, &context()).expect_err("must fail");

    let msg = format!("{err:#}");
    assert!(msg.contains("backend/.env.local"), "{msg}");
    assert!(
        msg.contains(&fx.main.display().to_string()),
        "should point at the main checkout, not this worktree: {msg}"
    );
}
