//! Producing an instance's env files.
//!
//! The source is always the main checkout. A worktree never inherits gitignored files, so
//! the human's working `.env.local` is the only copy that exists — and reading the real
//! file rather than `.env.example` also carries values that validators reject as
//! placeholders.

use anyhow::{Context as _, Result, bail};
use minijinja::{Environment, UndefinedBehavior, Value};
use std::collections::BTreeMap;
use std::path::PathBuf;

const HEADER: &str = "# generated by treeish -- do not edit";

pub struct Context {
    pub slug: String,
    pub ports: BTreeMap<String, u16>,
    pub db_name: Option<String>,
    pub main_worktree: PathBuf,
}

impl Context {
    fn bindings(&self) -> Value {
        let ports: BTreeMap<&str, u16> = self.ports.iter().map(|(k, v)| (k.as_str(), *v)).collect();
        let db = BTreeMap::from([("name", self.db_name.clone().unwrap_or_default())]);
        Value::from_serialize(BTreeMap::from([
            ("slug", Value::from(self.slug.as_str())),
            ("port", Value::from_serialize(&ports)),
            ("db", Value::from_serialize(&db)),
            (
                "main_worktree",
                Value::from(self.main_worktree.to_string_lossy().into_owned()),
            ),
        ]))
    }
}

/// Write every `[[secrets]]` file this repo declares, reading each from the main checkout
/// and writing it into the worktree. Returns what was written.
pub fn all(
    config: &crate::config::Config,
    resolved: &crate::resolve::Resolved,
    context: &Context,
) -> Result<Vec<PathBuf>> {
    let mut written = Vec::new();

    for secrets in &config.secrets {
        let source_path = resolved.main_worktree.join(&secrets.from);
        let source = match std::fs::read_to_string(&source_path) {
            Ok(text) => text,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => bail!(
                "{} is missing from the main checkout at {}\n\
                 treeish reads secrets from there because a worktree never inherits \
                 gitignored files. Create it in the main checkout first, then run \
                 `treeish up` again.",
                secrets.from,
                resolved.main_worktree.display()
            ),
            Err(e) => {
                return Err(e).with_context(|| format!("reading {}", source_path.display()));
            }
        };

        let destination = resolved.worktree.join(&secrets.into);
        if let Some(parent) = destination.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
        let body = env(&source, &secrets.set, context)
            .with_context(|| format!("rendering {}", secrets.into))?;
        std::fs::write(&destination, body)
            .with_context(|| format!("writing {}", destination.display()))?;
        written.push(destination);
    }

    Ok(written)
}

/// Rewrite `source` with `set` applied, as raw text: existing keys are replaced where
/// they sit and new ones appended. Parsing into a map and re-emitting would lose the
/// comments and ordering a human navigates their real env file by.
pub fn env(source: &str, set: &BTreeMap<String, String>, context: &Context) -> Result<String> {
    let bindings = context.bindings();
    let resolved: BTreeMap<&str, String> = set
        .iter()
        .map(|(k, v)| Ok((k.as_str(), template(v, &bindings)?)))
        .collect::<Result<_>>()?;

    let mut written: Vec<&str> = Vec::new();
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(&format!(
        "\n# source: {}\n",
        context.main_worktree.display()
    ));

    for line in source.lines() {
        match key_of(line) {
            Some(key) if resolved.contains_key(key) => {
                let key = resolved.get_key_value(key).expect("checked").0;
                out.push_str(&format!("{key}={}\n", resolved[key]));
                written.push(key);
            }
            _ => {
                out.push_str(line);
                out.push('\n');
            }
        }
    }

    for (key, value) in &resolved {
        if !written.contains(key) {
            out.push_str(&format!("{key}={value}\n"));
        }
    }

    Ok(out)
}

/// The key a line assigns, or `None` for blanks, comments, and anything unparseable.
/// A commented-out assignment is deliberately not a key: rewriting it would leave the
/// live value in place and point the instance somewhere else without saying so.
fn key_of(line: &str) -> Option<&str> {
    let trimmed = line.trim_start();
    if trimmed.is_empty() || trimmed.starts_with('#') {
        return None;
    }
    let assignment = trimmed.strip_prefix("export ").unwrap_or(trimmed);
    let key = assignment.split('=').next()?.trim();
    let valid = !key.is_empty()
        && key
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.');
    valid.then_some(key)
}

fn template(source: &str, bindings: &Value) -> Result<String> {
    let mut environment = Environment::new();
    // Strict: an unknown `{{ port.backned }}` must fail loudly rather than render empty
    // and produce a URL like `http://localhost:/` that fails far from its cause.
    environment.set_undefined_behavior(UndefinedBehavior::Strict);
    environment
        .add_template("value", source)
        .with_context(|| format!("parsing template {source:?}"))?;
    let template = environment.get_template("value").expect("just added");
    match template.render(bindings) {
        Ok(rendered) => Ok(rendered),
        Err(e) => bail!("rendering {source:?}: {e}"),
    }
}
